apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: echo
spec:
  params:
    - name: message
      description: The message to echo
      type: string
      default: "Hello, World!"  # Provide a default value
  tasks:
    - name: echo-task
      taskRef:
        name: echo
      params:
        - name: message
          value: "$(params.message)"
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: checkout
spec:
  params:
    - name: repo-url
      description: The URL of the git repo to clone
      type: string
    - name: branch
      description: The branch to clone
      type: string
  steps:
    - name: checkout
      image: bitnami/git:latest
      command: [git]
      args: ["clone", "--branch", "$(params.branch)", "$(params.repo-url)"]
